baseURL: "https://weizhang-econometrics.github.io/" 
title: Wei Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: 

taxonomies:
    tag: tags

menu:
    main:
        - name: Job Market Paper
          url: /BMDFM.pdf
          weight: 1  
        - name: CV
          url: /cv/
          weight: 2
        - name: Projects
          url: /papers/
          weight: 3
        - name: Teaching
          url: /courses/
          weight: 3

params:
    description: "I am a PhD student in Economics at Purdue University."
    author: Wei Zhang
    googleAnalyticsID: "G-D54BS9DFQ6"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Wei Zhang
          subtitle: "Welcome to my website! I am a PhD candidate in economics at Purdue University, working under the supervision of Professor [<u>Joshua C. C. Chan</u>](https://joshuachan.org/).
           <br>  <br> In general, I am interested in Bayesian model comparison, time series models and variational inference. Currently I focus on developing high-dimensional time series models for empirical macroeconomics or financial economics, including Bayesian large VARs, dynamic factor models, and stochastic volatility models."
          imageUrl: "/temp_photo.jpg"
          imageWidth: 250
          imageHeight: 250
          imageTitle: 
          buttons:
            - name: Job Market Paper
              url: https://arxiv.org/pdf/2409.08354
            - name: CV
              url: "/CV_0929.pdf"   
    socialIcons:
        - name: CV
          url: /CV_0919.pdf
        - name: Email
          url: mailto:zhan3721@purdue.edu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/WeiZhang-Econometrics

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Wei Zhang"
      icon: /favicon-whale.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

