baseURL: "https://weizhang-econometrics.github.io/"
title: Wei Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: papers/
          weight: 1
        - name: CV/Resume
          url: cv/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
#        - name: About Me
#          url: about/
#          weight: 3
##        - name: Newsletter
##          url: https://pmichaillat.substack.com
#          weight: 4

params:
    description: "I am a sixth year Ph.D. student in Economics at Purdue University."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Wei Zhang
          subtitle: "Welcome to my website! I am a PhD candidate in economics at Purdue University, working under the supervision of Professor [<u>Joshua C. C. Chan</u>](https://joshuachan.org/).
           <br>  <br> My research interests focus on developing high-dimensional time series models for empirical macroeconomics or financial economics, including Bayesian large VARs, dynamic factor models, and stochastic volatility models. <b>I am on the 2024-2025 job market.<b>"
          imageUrl: "/photo_square.png"
          imageWidth: 250
          imageHeight: 250
          imageTitle: Wei Zhang
          buttons:
            - name: Research
              url: papers/
            - name: CV / Resume
              url: cv/
            - name: Teaching
              url: courses/
#            - name: About Me
#              url: about/
#            - name: Newsletter
#              url: https://pmichaillat.substack.com
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
    socialIcons:
        - name: CV
          url: CV_0929.pdf
        - name: Email
          url: mailto:zhan3721@purdue.edu
        - name: Location
          url: location/
#        - name: Office Hours
#          url: officehours/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#        - name: YouTube
#          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/WeiZhang-Econometrics
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: Twitter
#          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Wei Zhang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
